base_model: Qwen/Qwen2.5-VL-3B-Instruct
processor_type: AutoProcessor

# these 3 lines are needed for now to handle vision chat templates w images
skip_prepare_dataset: true
remove_unused_columns: false
sample_packing: false

chat_template: qwen2_vl
datasets:
  - path: e-zorzi/reasoning_distractors_choice_chat_small
    type: chat_template
    split: train

dataset_prepared_path: last_run_prepared

test_datasets:
  - path: e-zorzi/reasoning_distractors_choice_chat_small
    type: chat_template
    split: val_seen[:10%]
  - path: e-zorzi/reasoning_distractors_choice_chat_small
    type: chat_template
    split: val_unseen[:10%]

output_dir: ./outputs/qwen2_5_VL_3B_lora_choice

load_in_8bit: True
adapter: lora
lora_model_dir:

sequence_len: 2046 #8192
pad_to_sequence_len: false

lora_r: 128
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

wandb_project: axolotl_finetunes
wandb_entity: edo_vi
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 16
num_epochs: 15
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: true
fp16:
tf32: true

gradient_checkpointing: true
logging_steps: 1
flash_attention: true
eager_attention:

warmup_ratio: 0.0067
evals_per_epoch: 3
saves_per_epoch: 1
save_strategy: epoch
weight_decay: 0.0

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config
